
import { Product, ProductCategory } from './types';

const now = new Date().toISOString();

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod_1',
    name: 'Refrigerador Inteligente',
    description: 'Refrigerador de 2 puertas con dispensador de agua y conexión Wi-Fi.',
    price: 1299.99,
    stock: 15,
    category: ProductCategory.APPLIANCES,
    imageUrl: 'https://picsum.photos/seed/fridge/400/400',
    created_at: now,
  },
  {
    id: 'prod_2',
    name: 'Cafetera Espresso Automática',
    description: 'Prepara cappuccinos y lattes con solo tocar un botón.',
    price: 349.50,
    stock: 30,
    category: ProductCategory.APPLIANCES,
    imageUrl: 'https://picsum.photos/seed/coffee/400/400',
    created_at: now,
  },
  {
    id: 'prod_3',
    name: 'Aceite de Oliva Extra Virgen',
    description: 'Botella de 750ml de aceite de oliva prensado en frío.',
    price: 12.99,
    stock: 150,
    category: ProductCategory.FOOD,
    imageUrl: 'https://picsum.photos/seed/oil/400/400',
    created_at: now,
  },
  {
    id: 'prod_4',
    name: 'Arroz Basmati Premium',
    description: 'Paquete de 5kg de arroz basmati de grano largo.',
    price: 22.00,
    stock: 200,
    category: ProductCategory.FOOD,
    imageUrl: 'https://picsum.photos/seed/rice/400/400',
    created_at: now,
  },
  {
    id: 'prod_5',
    name: 'Licuadora de Alta Potencia',
    description: '1200W de potencia para triturar hielo, frutas y vegetales.',
    price: 89.99,
    stock: 45,
    category: ProductCategory.APPLIANCES,
    imageUrl: 'https://picsum.photos/seed/blender/400/400',
    created_at: now,
  },
  {
    id: 'prod_6',
    name: 'Pasta de Tomate Orgánica',
    description: 'Lata de 400g de pasta de tomate sin conservantes.',
    price: 2.50,
    stock: 300,
    category: ProductCategory.FOOD,
    imageUrl: 'https://picsum.photos/seed/tomato/400/400',
    created_at: now,
  },
    {
    id: 'prod_7',
    name: 'Microondas Inverter',
    description: 'Horno de microondas con tecnología inverter para una cocción uniforme.',
    price: 199.99,
    stock: 25,
    category: ProductCategory.APPLIANCES,
    imageUrl: 'https://picsum.photos/seed/microwave/400/400',
    created_at: now,
  },
  {
    id: 'prod_8',
    name: 'Cereal de Avena y Miel',
    description: 'Caja de 500g de cereal integral de avena con miel.',
    price: 5.75,
    stock: 120,
    category: ProductCategory.FOOD,
    imageUrl: 'https://picsum.photos/seed/cereal/400/400',
    created_at: now,
  }
];
